### ISSUE TITLE
Hide the cursor in inactive windows

### ISSUE THREAD

**Issue by zoliky** [rememberYou/.emacs.d#10]
Hi Terencio, the variable `cursor-in-non-selected-windows` needs to be set to `nil` in order for Emacs to hide the cursor in inactive windows. However, in your configuration, it is currently set to `t`.

**Comment by rememberYou** [comment]
Hi Zoliky,
Yes, this variable was defined as `t` in my configuration. This [has been changed](https://github.com/rememberYou/.emacs.d/commit/044c46ee07646154f0193507b6ec43f57b705712). Thanks for your kind attention 🙂
