### ISSUE TITLE
IRC errors

### ISSUE THREAD

**Issue by fuzunspm** [rememberYou/.emacs.d#5]
I used your IRC config but ERC gives me trouble on starting emacs. Both erc-image and erc-hl-nicks can't be installed with the error below

```Error loading autoloads: (void-variable erc-mode-map)```
```Error void function: (define-erc-mode)```

**Comment by rememberYou** [comment]
Have you configured the sources of the packages and install `erc-hl-nicks` + `erc-image` using `use-package` or `require`?

To make it easier for you to install the packages, make sure you have at least these sources of packages:
```
(setq package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
                         ("melpa" . "http://melpa.org/packages/")
                         ("org" . "http://orgmode.org/elpa/")))
```

In addition to the `erc` config, make sure to install `erc-hl-nicks `and `erc-images`:
```
(use-package erc-hl-nicks :after erc)
(use-package erc-image :after erc)
```

Hopefully this will solve your problem, if not, I would need you to provide more information such as knowing your package sources and looking to your ERC configuration 🙂

**Comment by fuzunspm** [comment]
I just copied your erc config with commenting circe config and yes i'm using the same sources for packages.

this is the full error message on starting emacs.

```
Debugger entered--Lisp error: (void-variable erc-modules)
  (member (quote notifications) erc-modules)
  (if (member (quote notifications) erc-modules) erc-modules (setq erc-modules (cons (quote notifications) erc-modules)))
  (progn (if (member (quote notifications) erc-modules) erc-modules (setq erc-modules (cons (quote notifications) erc-modules))) (if (member (quote spelling) erc-modules) erc-modules (setq erc-modules (cons (quote spelling) erc-modules))) (erc-services-mode 1) (erc-update-modules) (if (fboundp (quote delight)) (delight (quote ((erc-mode "ε " erc))))) t)
  (condition-case err (progn (if (member (quote notifications) erc-modules) erc-modules (setq erc-modules (cons (quote notifications) erc-modules))) (if (member (quote spelling) erc-modules) erc-modules (setq erc-modules (cons (quote spelling) erc-modules))) (erc-services-mode 1) (erc-update-modules) (if (fboundp (quote delight)) (delight (quote ((erc-mode "ε " erc))))) t) ((debug error) (funcall use-package--warning3 :config err)))
  (closure (t) nil (condition-case err (progn (if (member (quote notifications) erc-modules) erc-modules (setq erc-modules (cons (quote notifications) erc-modules))) (if (member (quote spelling) erc-modules) erc-modules (setq erc-modules (cons (quote spelling) erc-modules))) (erc-services-mode 1) (erc-update-modules) (if (fboundp (quote delight)) (delight (quote ((erc-mode "ε " erc))))) t) ((debug error) (funcall use-package--warning3 :config err))))()
  eval-after-load-helper("/home/username/.emacs.d/lisp/erc.el")
  run-hook-with-args(eval-after-load-helper "/home/username/.emacs.d/lisp/erc.el")
  do-after-load-evaluation("/home/username/.emacs.d/lisp/erc.el")
  load-with-code-conversion("/home/username/.emacs.d/lisp/erc.el" "/home/username/.emacs.d/lisp/erc.el" nil t)
  #<subr require>(erc)
  apply(#<subr require> erc nil)
  (prog1 (apply orig feature args) (if (and (not already-loaded) (memq feature features)) (progn (let ((time (sanityinc/time-subtract-millis (current-time) require-start-time))) (add-to-list (quote sanityinc/require-times) (list feature require-start-time time) t)))))
  (let* ((already-loaded (memq feature features)) (require-start-time (and (not already-loaded) (current-time)))) (prog1 (apply orig feature args) (if (and (not already-loaded) (memq feature features)) (progn (let ((time (sanityinc/time-subtract-millis ... require-start-time))) (add-to-list (quote sanityinc/require-times) (list feature require-start-time time) t))))))
  sanityinc/require-times-wrapper(#<subr require> erc)
  apply(sanityinc/require-times-wrapper #<subr require> erc)
  require(erc)
  eval-buffer(#<buffer  *load*> nil "/home/username/.emacs.d/init.el" nil t)  ; Reading at buffer position 2723
  load-with-code-conversion("/home/username/.emacs.d/init.el" "/home/username/.emacs.d/init.el" t t)
  load("/home/username/.emacs.d/init" t t)
  #f(compiled-function () #<bytecode 0x1df6a1>)()
  command-line()
  normal-top-level()

```

**Comment by rememberYou** [comment]
The error message is quite explicit, the problem comes from `erc-modules` which is a variable defined in the `erc` package to load your modules.

With that in mind, I invite you to temporarily comment on the following two lines:
```
(add-to-list 'erc-modules 'notifications)
(add-to-list 'erc-modules 'spelling)
```

Then, to see if `erc-hl-nicks` as well as `erc-image` works well.

If so, we can focus in more detail on `erc-modules` 🙂

**Comment by fuzunspm** [comment]
```
Debugger entered--Lisp error: (void-function erc-make-obsolete)
  (erc-make-obsolete (quote erc-current-network) (quote erc-network) "Obsolete since erc-networks 1.5")
```

**Comment by rememberYou** [comment]
So I guess you still have the error, even when you comment on the previous lines.

Can you specify your version of GNU Emacs with `emacs-version`?

**Comment by fuzunspm** [comment]
yes commenting those lines are generated a new error.

my emacs version is 26.3

**Comment by rememberYou** [comment]
At first glance, I have no idea. I recommend that you gradually comment on your `erc` configuration until you find the line(s) that are causing problems.

Do not hesitate to ask your question about IRC/Reddit if you want a quick answer 🙂

**Comment by fuzunspm** [comment]
ah silly me, i typo in ```(provide 'ercc)``` at the end of erc init file. It's fully working now except dbus on macos but it has nothing to do with your config. 

In addition to that, i followed your guide to read username and password from gpg file but it still requires to input username and password on first launch

**Comment by rememberYou** [comment]
Glad to see you were able to find the solution 🙂

For authentication, be sure to have this line of code in your ERC configuration:
`(setq erc-prompt-for-nickserv-password nil)`

Actually, it allows GNU Emacs to tell it that you are using a third-party file to connect to ERC.
