### ISSUE TITLE
Stuck with Emacs asking for password for /sudo:root@machine:

### ISSUE THREAD

**Issue by chupinmaxime** [rememberYou/.emacs.d#8]
Hi,
Thanks for your sharing!
Unfortunately, when I try to run Emacs, I'm stuck with Emacs asking:
```
Password for /sudo:root@machine:
```
and I do not know why. 

Thanks in advance.

**Comment by rememberYou** [comment]
Hey,

  This behavior is normal if you copied and pasted my entire GNU Emacs configuration. For some packages (e.g., `markdown-mode`) I use a `use-package` statement that automatically installs missing packages using my package manager system (`yay`) like shown below:
```elisp
(use-package markdown-mode
  :delight "μ"
  :ensure-system-package (pandoc . "yay -S pandoc") ;; <-- Install pandoc if not available
  :mode ("\\.\\(md\\|markdown\\)\\'")
  :custom (markdown-command "/usr/bin/pandoc"))
```

To avoid this, you can remove the `:ensure-system-package` instructions or type the password needed to give the rights to GNU Emacs to allow it to install these packages. Let me know if the error still persists! :-)

I will probably refactor this configuration soon to make it more generic.
